version: "3.8"
services:
  superset:
    image: superset-custom
    container_name: superset_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8088:8088"
    env_file:
      - superset.env
    volumes:
      - ./superset_home:/app/superset_home
      - ./superset_config.py:/app/pythonpath/superset_config.py
    dns:
      - 8.8.8.8
    restart: always
    depends_on:
      - redis

  superset-init:
    image: superset-custom
    container_name: superset_init
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      /bin/sh -c "superset fab create-admin --username $${SUPERSET_USERNAME:-admin} --firstname Superset --lastname Admin --email admin@example.com --password $${SUPERSET_PASSWORD:-admin} && superset db upgrade && superset init"
    env_file:
      - superset.env
    volumes:
      - ./superset_home:/app/superset_home
      - ./superset_config.py:/app/pythonpath/superset_config.py
    dns:
      - 8.8.8.8
    depends_on:
      - redis

  redis:
    image: redis:7
    container_name: superset_redis
    restart: always

volumes:
  superset_home:
